# Generated by Django 5.1.5 on 2026-08-03 10:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('supabase_uid', models.UUIDField(db_index=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('full_name', models.CharField(blank=True, max_length=160)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('avatar_url', models.URLField(blank=True, max_length=500)),
                ('role', models.CharField(blank=True, choices=[('buyer', 'Buyer'), ('supplier', 'Supplier'), ('admin', 'Admin')], max_length=16)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('tshirt', 'T-Shirts'), ('polo', 'Polo'), ('denim', 'Denim'), ('knitwear', 'Knitwear'), ('woven', 'Woven'), ('fleece', 'Fleece'), ('hoodie', 'Hoodie / Sweatshirt'), ('trouser', 'Trousers'), ('kidswear', 'Kidswear'), ('activewear', 'Activewear'), ('other', 'Other')], default='other', max_length=24)),
                ('gsm', models.PositiveIntegerField(help_text='Grams per square metre', validators=[django.core.validators.MinValueValidator(1)])),
                ('fabric_composition', models.CharField(help_text='e.g. 95% Cotton, 5% Elastane', max_length=160)),
                ('sizes_available', models.CharField(blank=True, help_text='Comma separated, e.g. S,M,L,XL', max_length=160)),
                ('colors', models.CharField(blank=True, max_length=160)),
                ('available_quantity', models.PositiveIntegerField()),
                ('moq', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Minimum order quantity')),
                ('unit_price_bdt', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('estimated_transport_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('images', models.JSONField(blank=True, default=list, help_text='List of Supabase Storage public URLs')),
                ('location', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BuyerProfile',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=160)),
                ('business_type', models.CharField(blank=True, max_length=120)),
                ('contact_phone', models.CharField(max_length=32)),
                ('address', models.TextField()),
                ('district', models.CharField(blank=True, max_length=80)),
                ('nid_number', models.CharField(blank=True, max_length=40)),
                ('nid_document_url', models.URLField(blank=True, max_length=500)),
                ('verification_status', models.CharField(choices=[('unsubmitted', 'Not submitted'), ('pending', 'Pending review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='unsubmitted', max_length=16)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_profile', to='core.account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=20, unique=True)),
                ('ordered_quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price_bdt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transport_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('bkash', 'bKash'), ('card', 'Card'), ('cod', 'Cash on Delivery')], default='cod', max_length=12)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('due_on_delivery', 'Due on Delivery'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=80)),
                ('order_status', models.CharField(choices=[('placed', 'Order Placed'), ('confirmed', 'Confirmed by Supplier'), ('dispatched', 'Dispatched'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='placed', max_length=16)),
                ('delivery_address', models.TextField()),
                ('delivery_district', models.CharField(blank=True, max_length=80)),
                ('contact_person', models.CharField(max_length=120)),
                ('contact_phone', models.CharField(max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('buyer_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('buyer_review', models.TextField(blank=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.buyerprofile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('placed', 'Order Placed'), ('confirmed', 'Confirmed by Supplier'), ('dispatched', 'Dispatched'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=16)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_by', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.order')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierProfile',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=160)),
                ('contact_phone', models.CharField(max_length=32)),
                ('address', models.TextField()),
                ('district', models.CharField(blank=True, max_length=80)),
                ('trade_license_number', models.CharField(blank=True, max_length=60)),
                ('trade_license_document_url', models.URLField(blank=True, max_length=500)),
                ('nid_number', models.CharField(blank=True, max_length=40)),
                ('about', models.TextField(blank=True)),
                ('verification_status', models.CharField(choices=[('unsubmitted', 'Not submitted'), ('pending', 'Pending review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='unsubmitted', max_length=16)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_profile', to='core.account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.supplierprofile'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_status', '-created_at'], name='core_order_order_s_5b09f8_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='core_produc_categor_ba410e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['gsm'], name='core_produc_gsm_299250_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['unit_price_bdt'], name='core_produc_unit_pr_b41c9e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', '-created_at'], name='core_produc_is_acti_c98122_idx'),
        ),
    ]
