# Generated by Django 5.1.5 on 2026-08-03 13:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationRequest',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Awaiting supplier review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn by buyer')], default='pending', max_length=12)),
                ('response_note', models.CharField(blank=True, max_length=300)),
                ('resolved_by', models.CharField(blank=True, max_length=120)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='nid_back_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_by_buyer',
            field=models.BooleanField(default=False, help_text='Only buyer-initiated cancellations count against the monthly quota.'),
        ),
        migrations.AddField(
            model_name='order',
            name='commission_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0200'), max_digits=5),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_speed',
            field=models.CharField(choices=[('standard', 'Standard Delivery'), ('express', 'Express Delivery')], default='standard', max_length=12),
        ),
        migrations.AddField(
            model_name='order',
            name='express_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='platform_commission',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='promised_delivery_at',
            field=models.DateTimeField(blank=True, help_text='Express orders carry a delivery guarantee.', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='supplier_payout',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='express_delivery_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='express_delivery_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='express_delivery_hours',
            field=models.PositiveIntegerField(default=24, help_text='Guaranteed delivery window when express is chosen.'),
        ),
        migrations.AddField(
            model_name='product',
            name='free_delivery',
            field=models.BooleanField(default=False, help_text='Supplier absorbs transport. Forces the transport cost to zero.'),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='nid_back_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='nid_document_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['cancelled_at'], name='core_order_cancell_eea468_idx'),
        ),
        migrations.AddField(
            model_name='cancellationrequest',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_requests', to='core.order'),
        ),
    ]
